version: "3.3"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins_declarative-pipeline
    container_name: jenkins_declarative-pipeline
    volumes:
      # jenkins persistent jenkins
      - ./jenkins_home:/var/jenkins_home
      # jenkins.yaml
      - ./casc_configs:/var/jenkins_conf
      - ./job_dsls:/var/jenkins_job/job_dsls
    environment:
      # docker-in-docker
      - DOCKER_HOST=tcp://socat:2375
      # jenkins.yaml
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
      # java configuration
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8
    secrets:
        - adminuser # should be remove before production
        - adminpw # should be remove before production
        - github # should be remove before production
    ports:
      - 50003:50000
      - 8084:8080
    links:
      - socat

  # user socat to achieve docker-in-docker for jenkins user without `usermod -a -G docker jenkins` or `chmod 664 /var/run/docker.sock`.
  # ref: https://medium.com/@mingheng/solving-permission-denied-while-trying-to-connect-to-docker-daemon-socket-from-container-in-mac-os-600c457f1276
  socat:
     image: bpack/socat
     command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock
     volumes:
        - /var/run/docker.sock:/var/run/docker.sock
     expose:
        - "2375"

# secrets for Jenkins Configuration As Code (cac)
secrets:
  adminuser:
    file: ./secrets/adminUser
  adminpw:
    file: ./secrets/adminpw
  github:
    file: ./secrets/github
