version: "2"
services:
  jenkins:
    container_name: jenkins_wolox
    image: jenkins/jenkins:lts
    volumes:
      # optional: jenkins persistent jenkins
      - ./jenkins_home:/var/jenkins_home
      # optional: logging & plugin
      - ./config:/var/jenkins_config
      # optional: jenkins system configuration
      - ./init.groovy/executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy
    environment:
      # optional: logging handling
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Djava.util.logging.config.file=/var/jenkins_config/log.properties
    ports:
      - 50000:50000
      - 8081:8080
