version: "2"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins_declarative-pipeline
    container_name: jenkins_declarative-pipeline
    volumes:
      # docker in docker
      - /var/run/docker.sock:/var/run/docker.sock
      # optional: jenkins persistent jenkins
      - ./jenkins_home:/var/jenkins_home
      # optional: logging
      #- ./config:/var/jenkins_config
      # optional: jenkins system configuration
      - ./init.groovy/executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8
      # optional: logging handling
      #- JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Djava.util.logging.config.file=/var/jenkins_config/log.properties
    ports:
      - 50003:50000
      - 8083:8080
